config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'samples/show'
  devise_for :users, controllers: {
    # controllerのオーバーライド
    registrations: 'users/registrations'
  }
  root to: 'homes#top'
  get 'home/about', to: 'homes#about'
  resources :users, only: %i[index show edit update] do
    resources :relationships, only: %i[create destroy]
    get 'relationships/following', to: 'relationships#following'
    get 'relationships/follower', to: 'relationships#follower'

    # チャット機能
    resources :rooms, only: %i[show create] do
      resources :chats, only: [:create]
    end
  end

  resources :books, only: %i[index show create edit update destroy] do
    resources :favorites, only: %i[create destroy]
    resources :book_comments, only: %i[create destroy]
  end

  get 'searches/result', to: 'searches#search'
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # バリデーション設定
  validates :name,          presence: true # 空欄でないこと
  validates :name,          length: { minimum: 2 }      # 2文字以上
  validates :name,          length: { maximum: 20 }     # 20文字以下
  validates :name,          uniqueness: true # 一意であること
  validates :introduction,  length: { maximum: 50 } # 50文字以下

  #  他のモデルとの関連付け
  has_many :books, dependent: :destroy
  has_many :favorites
  has_many :book_comments
  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy

  # フォローする関係
  has_many :follow_relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  # @user.followinhgsで、ユーザがフォローしている人の一覧を出す
  has_many :followings, through: :follow_relationships, source: :followed

  # フォローされる関係
  has_many :followed_relationships, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  # @user.followedsで、ユーザをフォローしている人の一覧を出す
  has_many :followeds, through: :followed_relationships, source: :follower

  # refile用の設定
  attachment :profile_image

  #  あるユーザを自分がフォローしているか調べる
  def following?(target_user)
    followings.include?(target_user)
  end

  # 住所自動入力
  include JpPrefecture
  jp_prefecture :prefecture_code

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

# deviseのRegistrationsControllerをオーバーライド
module Users
  class RegistrationsController < Devise::RegistrationsController
    def create
      # 親クラスを継承
      super
      # 新規登録成功時にメール送信
      ThanksMailer.thanks_email(@user).deliver unless @user.invalid?
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @books = Book.where(user_id: params[:id])

    # チャット機能
    # user_roomテーブルからレコードを特定する
    userRoomsCurrentUser = UserRoom.where(user_id: current_user.id)
    userRoomsPartnerUser = UserRoom.where(user_id: @user.id)
    userRoom = find_user_room(userRoomsCurrentUser, userRoomsPartnerUser)
    if userRoom.present?
      # 特定したuser_roomのレコードからroom_idを取得
      @roomId = userRoom.room_id
      @RoomExist = true
    else
      # そもそもuser_roomにレコードがなければ、レコードを作成
      @userRoom = UserRoom.new
      @room = Room.new
      @RoomExist = false
    end
  end

  def edit
    @user = User.find(params[:id])
    redirect_to user_path(current_user) if current_user != @user
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = 'You have updated user successfully.'
      redirect_to user_path(params[:id])
    else
      render :edit
    end
  end

  private

  # ストロングパラメータ
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image_id)
  end

  # user_roomテーブルのレコードを特定する
  def find_user_room(userRooms1, userRooms2)
    userRooms1.each do |ur1|
      userRooms2.each do |ur2|
        return userRoom = UserRoom.find(ur1.id) if ur1.room_id == ur2.room_id
      end
    end
    # レコードがなかった時
    nil
  end
end

app/helpers/user_helper.rb
# frozen_string_literal: true

module UserHelper
end

app/views/users/_follow.html.slim
- if not current_user.id == user.id
  - if current_user.following?(user)
    = link_to "フォロー外す", user_relationship_path(user.id, current_user.id), method: :delete
  - else
    = link_to "フォローする", user_relationships_path(user.id), method: :post

app/views/users/_users_table.html.slim
table.table.table-hover.table-inverse
  thead
    tr
      th
        | image
      th
        | name
      th[colspan="4"]
  - users.each do |user|
    tbody
      tr
        td
          = attachment_image_tag user, :profile_image, size:'40x40', fallback: "no_image.jpg"
        td
          = user.name
        td
          p
            | フォロー数：
            = user.followings.count
        td
          p
            | フォロワー数：
            = user.followeds.count
        td
          = render 'users/follow', user: user
        td
          = link_to 'Show', user_path(user)

app/views/users/edit.html.slim
.container
  .row
    .col-sm-12.col-md-8.col-lg-5.px-5.px-sm-0.mx-auto
      h2
        | User info
      = render 'layouts/error_messages', value: @user
      = form_with model: @user, local: true do |f|
        .form-group
          label[for="user_name"]
            | Name
          |  <input type="text" class="form-control" id="user_name" name='user[name]' value=
          = @user.name
          |  >
        .form-group
          label[for="user_profile_image"]
            | Image
          input#profile_image.form-control-file[type="file" name="user[profile_image]"]
        .form-group
          label[for="user_introduction"]
            | Introduction
          textarea#user_introduction.form-control[name="user[introduction]"]
            = @user.introduction
        .form-group
          button.btn.btn-secondary[type="submit"]
            | Update User

app/views/users/index.html.slim
.container
  .row
    .col-md-3
      = render 'layouts/sidebar', user: current_user, book: @newbook
    .col-md-8.offset-md-1
      h2
        | Users
      = render 'users/users_table', users: @users

app/views/users/show.html.slim
.container
  .row
    .col-md-3
      = render 'layouts/sidebar', user: @user, book: @book
    .col-md-8.offset-md-1
      h2
        | Books
      table.table.table-hover.table-inverse
        thead
          tr
            th
            th
              | Title
            th
              | Opinion
            th[colspan="3"]
        tbody
          - @books.each do |book|
            tr
              td
                = link_to user_path(params[:id]) do
                  = attachment_image_tag @user, :profile_image, size:'40x40', fallback: "no_image.jpg"
              td
                = link_to book_path(book) do
                  = book.title
              td
                = book.body
              td
                p
                  | コメント数：
                  = book.commented_count