config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'samples/show'
  devise_for :users, controllers: {
    # controllerのオーバーライド
    registrations: 'users/registrations'
  }
  root to: 'homes#top'
  get 'home/about', to: 'homes#about'
  resources :users, only: %i[index show edit update] do
    resources :relationships, only: %i[create destroy]
    get 'relationships/following', to: 'relationships#following'
    get 'relationships/follower', to: 'relationships#follower'

    # チャット機能
    resources :rooms, only: %i[show create] do
      resources :chats, only: [:create]
    end
  end

  resources :books, only: %i[index show create edit update destroy] do
    resources :favorites, only: %i[create destroy]
    resources :book_comments, only: %i[create destroy]
  end

  get 'searches/result', to: 'searches#search'
end

app/models/book.rb
# frozen_string_literal: true

class Book < ApplicationRecord
  # バリデーション設定
  validates :title, presence: true              # 空欄でないこと
  validates :body,  presence: true              # 空欄でないこと
  validates :body,  length: { maximum: 200 } # 200文字以下

  #  他のモデルとの関連付け
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  # ユーザーが"いいね"したか調べる
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  # "いいね"されている数を返す
  def favorited_count
    if favorites.exists?
      favorites.count.to_s
    else
      '0'.to_s
    end
  end

  # コメントされている数を返す
  def commented_count
    if book_comments.exists?
      book_comments.count.to_s
    else
      '0'.to_s
    end
  end
end

app/controllers/books_controller.rb
# frozen_string_literal: true

class BooksController < ApplicationController
  def index
    @newbook = Book.new
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
    @user = User.find_by(id: @book.user_id)

    # コメント機能用
    @book_comments = BookComment.where(book_id: @book.id)
    @new_comment = BookComment.new
  end

  def create
    @newbook = Book.new(book_params)
    @newbook.user_id = current_user.id
    if @newbook.save
      flash[:success] = 'You have created book successfully.'
      redirect_to book_path(@newbook)
    else
      @books = Book.all
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
    redirect_to books_path if current_user != User.find(@book.user_id)
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:success] = 'You have updated book successfully.'
      redirect_to book_path(@book)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.delete
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/helpers/books_helper.rb
# frozen_string_literal: true

module BooksHelper
end

app/views/books/_books_table.html.slim
table.table.table-hover.table-inverse
  thead
    tr
      th
      th
        | Title
      th
        | Opinion
      th[colspan="2"]
  tbody
    - books.each do |book|
      tr
        td
          - user = User.find_by(id: book.user_id)
          = link_to user_path(user) do
            = attachment_image_tag user, :profile_image, size:'40x40', fallback: "no_image.jpg"
        td
          = link_to book_path(book) do
            = book.title
        td
          = book.body
        |  <td class=
        = 'favorite' + book.id.to_s
        | > 
        = render 'favorites/favorite', book: book
        td
          p
            | コメント数：
            = book.commented_count

app/views/books/_comment.html.erb
<!-- コメント一覧 -->
<h5>Comments</h5>

<table class='table table-hover table-inverse'>
  <!-- テーブル中身 -->
  <tbody>
    <% book_comments.each do |book_comment| %>
      <tr>
         <!-- 投稿ユーザ -->
        <td>
          <% user = User.find_by(id: book_comment.user_id) %>
          <%= link_to user_path(user) do %>
            <%= attachment_image_tag user, :profile_image, size:'40x40', fallback: "no_image.jpg" %><br>
            <%= user.name %>
          <% end %>
        </td>
        </td>
         <!-- コメント -->
        <td>
          <%= book_comment.comment %>
        </td>
        <!-- 本人の投稿の場合だけ削除ができる -->
        <% if book_comment.user_id == current_user.id %>
          <td>
            <%= link_to book_book_comment_path(book_comment.book_id , book_comment.id), method: :delete do %>
              <div class='btn btn-danger'>Destroy</div>
            <% end %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<!--コメント投稿フォーム -->
<%= form_with model: new_comment, url: book_book_comments_path(book), method: :post, local: true do |f| %>
  <div class="form-group">
    <label for="comment">New comment</label>
    <textarea class="form-control" id="comment" name='new_comment[comment]'></textarea>
  </div>
  <button type="submit" class="btn btn-secondary">送信</button>
<% end %>

app/views/books/_favorite.html.erb
<% if book.favorited_by?(current_user) %>

  <!-- current_userがいいねしている場合-->
  <%= link_to book_favorite_path(book.id, current_user.id), method: :delete do %>
    <i class="fas fa-heart"></i>
    <%= book.favorited_count %>
  <% end %>

<% else %>

  <!-- current_userがいいねしていない場合-->
  <%= link_to book_favorites_path(book.id), method: :post do %>
    <i class="far fa-heart"></i>
    <%= book.favorited_count %>
  <% end %>

<% end %>

app/views/books/edit.html.slim
.container
  .row
    .col-sm-12.col-md-8.col-lg-5.px-5.px-sm-0.mx-auto
      h1
        | Editing Book
      = render 'layouts/error_messages', value: @book
      = form_with model: @book, local: true do |f|
        .form-group
          label[for="book_title"]
            | Title
          |  <input type="text" class="form-control" id="book_title" name='book[title]' value=
          = @book.title
          |  > 
        .form-group
          label[for="book_opinion"]
            | Opinion
          textarea#book_opinion.form-control[name="book[body]"]
            = @book.body
        .form-group
          button.btn.btn-success[type="submit"]
            | Update Book
      = link_to 'Show', book_path(@book)
      |  | 
      = link_to 'Back', books_path

app/views/books/index.html.slim
.container
  = render 'layouts/error_messages', value: @newbook
  .row
    .col-md-3
      = render 'layouts/sidebar', user:current_user, book: @newbook
    .col-md-8.offset-md-1
      h2
        | Books
      = render 'books/books_table', books: @books

app/views/books/show.html.slim
= render 'layouts/error_messages', value: @new_comment
.container
  .row
    .col-md-3
      = render 'layouts/sidebar', user: @user, book: @newbook
    .col-md-8.offset-md-1
      h2
        | Book detail
      table.table.table-hover.table-inverse
        tbody
          tr
            td
              = link_to user_path(@user) do
                = attachment_image_tag @user, :profile_image, size:'40x40', fallback: "no_image.jpg"
                br
                = @user.name
            td
              = link_to book_path(@book) do
                = @book.title
            td
              = @book.body
            |  <td class=
            = 'favorite' + @book.id.to_s
            | > 
            = render 'favorites/favorite', book: @book
            td#comment_num
              p
                | コメント数：
                = @book.commented_count
            - if @book.user_id == current_user.id
              td
                = link_to edit_book_path(@book) do
                  .btn.btn-success
                    | Edit
              td
                = link_to book_path(@book), method: :delete do
                  .btn.btn-danger
                    | Destroy
      .comment_list
        = render "book_comments/comment", book: @book, book_comments: @book_comments, new_comment: @new_comment