config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'samples/show'
  devise_for :users, controllers: {
    # controllerのオーバーライド
    registrations: 'users/registrations'
  }
  root to: 'homes#top'
  get 'home/about', to: 'homes#about'
  resources :users, only: %i[index show edit update] do
    resources :relationships, only: %i[create destroy]
    get 'relationships/following', to: 'relationships#following'
    get 'relationships/follower', to: 'relationships#follower'

    # チャット機能
    resources :rooms, only: %i[show create] do
      resources :chats, only: [:create]
    end
  end

  resources :books, only: %i[index show create edit update destroy] do
    resources :favorites, only: %i[create destroy]
    resources :book_comments, only: %i[create destroy]
  end

  get 'searches/result', to: 'searches#search'
end

app/controllers/searches_controller.rb
# frozen_string_literal: true

class SearchesController < ApplicationController
  def search
    # 検索フォームから取得した情報
    @search_name = params[:name]        # 名前
    @search_target = params[:target]    # 検索するもの（User or Book）
    @search_how = params[:how]          # 検索手法（完全一致 or 前方一致 or 後方一致 or 部分一致）

    @results = if @search_target == 'User'
                 # 名前検索
                 case @search_how
                 when 'perfect'
                   # 完全一致
                   User.where('name like ?', @search_name.to_s)
                 when 'forward'
                   # 前方一致
                   User.where('name like ?', "#{@search_name}%")
                 when 'back'
                   # 後方一致
                   User.where('name like ?', "%#{@search_name}")
                 else
                   # 部分一致
                   User.where('name like ?', "%#{@search_name}%")
                 end
               else
                 # 書籍検索
                 case @search_how
                 when 'perfect'
                   # 完全一致
                   Book.where('title like ?', @search_name.to_s)
                 when 'forward'
                   # 前方一致
                   Book.where('title like ?', "#{@search_name}%")
                 when 'back'
                   # 後方一致
                   Book.where('title like ?', "%#{@search_name}")
                 else
                   # 部分一致
                   Book.where('title like ?', "%#{@search_name}%")
                 end
               end
  end
end

app/helpers/searches_helper.rb
# frozen_string_literal: true

module SearchesHelper
end

app/views/searches/_search.html.slim
- if user_signed_in?
  .container.mb-5
    .row
      .col-md-5.offset-md-5
        = form_with model: @search, url: searches_result_path, method: :get, local: true do |f|
          = f.text_field :name
          = f.select :target, [["User", "User"], ["Book", "Book"]]
          = f.select :how, [["完全一致", "perfect"], ["前方一致", "forward"], ["後方一致", "back"], ["部分一致", "part"]]
          = f.submit :検索

app/views/searches/search.html.slim
.container
  .row
    - if @search_target == "User"
      h2
        | Users search for '
        = @search_name
        | '
      = render 'users/users_table', users: @results
    - else
      h2
        | Books search for '
        = @search_name
        | '
      = render 'books/books_table', books: @results