config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'samples/show'
  devise_for :users, controllers: {
    # controllerのオーバーライド
    registrations: 'users/registrations'
  }
  root to: 'homes#top'
  get 'home/about', to: 'homes#about'
  resources :users, only: %i[index show edit update] do
    resources :relationships, only: %i[create destroy]
    get 'relationships/following', to: 'relationships#following'
    get 'relationships/follower', to: 'relationships#follower'

    # チャット機能
    resources :rooms, only: %i[show create] do
      resources :chats, only: [:create]
    end
  end

  resources :books, only: %i[index show create edit update destroy] do
    resources :favorites, only: %i[create destroy]
    resources :book_comments, only: %i[create destroy]
  end

  get 'searches/result', to: 'searches#search'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
# frozen_string_literal: true

class Book < ApplicationRecord
  # バリデーション設定
  validates :title, presence: true              # 空欄でないこと
  validates :body,  presence: true              # 空欄でないこと
  validates :body,  length: { maximum: 200 } # 200文字以下

  #  他のモデルとの関連付け
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  # ユーザーが"いいね"したか調べる
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  # "いいね"されている数を返す
  def favorited_count
    if favorites.exists?
      favorites.count.to_s
    else
      '0'.to_s
    end
  end

  # コメントされている数を返す
  def commented_count
    if book_comments.exists?
      book_comments.count.to_s
    else
      '0'.to_s
    end
  end
end

app/models/book_comment.rb
# frozen_string_literal: true

class BookComment < ApplicationRecord
  # バリデーション設定
  validates :user_id, presence: true  # 空欄でないこと
  validates :book_id, presence: true  # 空欄でないこと
  validates :comment, presence: true  # 空欄でないこと

  #  他のモデルとの関連付け
  belongs_to :book
end

app/models/chat.rb
# frozen_string_literal: true

class Chat < ApplicationRecord
  # バリデーション設定
  validates :message, presence: true # 空欄でないこと

  #  他のモデルとの関連付け
  has_many :users, dependent: :destroy
  has_many :rooms, dependent: :destroy
end

app/models/favorite.rb
# frozen_string_literal: true

class Favorite < ApplicationRecord
  # バリデーション設定
  validates :user_id,   presence: true                                # 空欄でないこと
  validates :book_id,   presence: true                                # 空欄でないこと
  validates :user_id,   uniqueness: { scope: %i[book_id] }            # ユーザは1つの投稿に1つしか"いいね"できない

  #  他のモデルとの関連付け
  belongs_to :book
end

app/models/relationship.rb
# frozen_string_literal: true

class Relationship < ApplicationRecord
  # バリデーション設定
  validates :id,          uniqueness: { scope: %i[follower_id followed_id] } # ユーザを二重にフォローすることはできない
  validates :follower_id, presence: true                                        # 空欄でないこと
  validates :followed_id, presence: true                                        # 空欄でないこと

  #  他のモデルとの関連付け
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
end

app/models/room.rb
# frozen_string_literal: true

class Room < ApplicationRecord
  #  他のモデルとの関連付け
  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # バリデーション設定
  validates :name,          presence: true # 空欄でないこと
  validates :name,          length: { minimum: 2 }      # 2文字以上
  validates :name,          length: { maximum: 20 }     # 20文字以下
  validates :name,          uniqueness: true # 一意であること
  validates :introduction,  length: { maximum: 50 } # 50文字以下

  #  他のモデルとの関連付け
  has_many :books, dependent: :destroy
  has_many :favorites
  has_many :book_comments
  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy

  # フォローする関係
  has_many :follow_relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  # @user.followinhgsで、ユーザがフォローしている人の一覧を出す
  has_many :followings, through: :follow_relationships, source: :followed

  # フォローされる関係
  has_many :followed_relationships, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  # @user.followedsで、ユーザをフォローしている人の一覧を出す
  has_many :followeds, through: :followed_relationships, source: :follower

  # refile用の設定
  attachment :profile_image

  #  あるユーザを自分がフォローしているか調べる
  def following?(target_user)
    followings.include?(target_user)
  end

  # 住所自動入力
  include JpPrefecture
  jp_prefecture :prefecture_code

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end
end

app/models/user_room.rb
# frozen_string_literal: true

class UserRoom < ApplicationRecord
  #  他のモデルとの関連付け
  has_many :users, dependent: :destroy
  has_many :rooms, dependent: :destroy
end

app/controllers/books_controller.rb
# frozen_string_literal: true

class BooksController < ApplicationController
  def index
    @newbook = Book.new
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
    @user = User.find_by(id: @book.user_id)

    # コメント機能用
    @book_comments = BookComment.where(book_id: @book.id)
    @new_comment = BookComment.new
  end

  def create
    @newbook = Book.new(book_params)
    @newbook.user_id = current_user.id
    if @newbook.save
      flash[:success] = 'You have created book successfully.'
      redirect_to book_path(@newbook)
    else
      @books = Book.all
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
    redirect_to books_path if current_user != User.find(@book.user_id)
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:success] = 'You have updated book successfully.'
      redirect_to book_path(@book)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.delete
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/chats_controller.rb
# frozen_string_literal: true

class ChatsController < ApplicationController
  def create
    # JavaScriptに渡すインスタンス変数
    @chats = Chat.where(room_id: params[:room_id])
    @partner_user = User.find(params[:user_id])
    @new_chat = Chat.new
    @room = Room.find(params[:room_id])

    # chat作成
    chat = Chat.new(chat_params)
    chat.user_id = current_user.id
    chat.room_id = params[:room_id]
    chat.save
  end

  private

  def chat_params
    params.require(:chat).permit(:message)
  end
end

app/controllers/homes_controller.rb
# frozen_string_literal: true

class HomesController < ApplicationController
  def top; end

  def about; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/books_helper.rb
# frozen_string_literal: true

module BooksHelper
end

app/helpers/chats_helper.rb
# frozen_string_literal: true

module ChatsHelper
end

app/helpers/favorites_helper.rb
# frozen_string_literal: true

module FavoritesHelper
end

app/helpers/homes_helper.rb
# frozen_string_literal: true

module HomesHelper
end

app/helpers/rooms_helper.rb
# frozen_string_literal: true

module RoomsHelper
end

app/helpers/searches_helper.rb
# frozen_string_literal: true

module SearchesHelper
end

app/helpers/user_helper.rb
# frozen_string_literal: true

module UserHelper
end

app/views/layouts/_error_messages.html.slim
.error_explanation
  - if value.errors.any?
    h3
      = value.errors.count
      |  error prohibited this obj from being saved:
    ul
      - value.errors.full_messages.each do |message|
        li
          = message

app/views/layouts/_footer.html.slim
.container.mt-5
  .row
    .mx-auto
      p
        | CopyRight Infratop.inc

app/views/layouts/_header.html.slim
.navbar.navbar-expand-lg.navbar-dark.bg-dark
  .container
    a.navbar-brand[href="/"]
      | Bookers
    button.navbar-toggler[type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation"]
      span.navbar-toggler-icon
    #navbarNavDropdown.collapse.navbar-collapse
      ul.navbar-nav.ml-auto
        - if user_signed_in?
          li
            = link_to " Home", user_path(current_user.id), class:"fas fa-home nav-link text-light"
          li
            = link_to " Users", users_path, class:"fas fa-users nav-link text-light"
          li
            = link_to " Books", books_path, class:"fas fa-book-open nav-link text-light"
          li
            = link_to " logout", destroy_user_session_path, method: :delete, class:"fas fa-sign-out-alt nav-link text-light"
        - else
          li
            = link_to " Home", root_path, class:"fas fa-home nav-link text-light"
          li
            = link_to " About", home_about_path, class:"fas fa-link nav-link text-light"
          li
            = link_to " sign up", new_user_registration_path, class:"fas fa-user-plus nav-link text-light", data: {"turbolinks" => false}
          li
            = link_to " login", new_user_session_path, class:"fas fa-sign-in-alt nav-link text-light"

app/views/layouts/_notifications.html.slim
- flash.each do |key, value|
  = content_tag(:span, value, class: key )

app/views/layouts/_sidebar.html.slim
h2
  | User info
= attachment_image_tag user, :profile_image, size:'100x100', fallback: "no_image.jpg"
table.table
  tbody
    tr
    tr
      th
        | Name
      th
        = user.name
    tr
      th
        | Introduction
      th
        = user.introduction
    tr
      th
        | Follows
      th
        = link_to user_relationships_following_path(user.id) do
          = user.followings.count
    tr
      th
        | Followers
      th
        = link_to user_relationships_follower_path(user.id) do
          = user.followeds.count
    tr
      th
        = render 'layouts/sidebar_follow', user: user
    - unless current_user.id == user.id
      tr
        th
          - if @RoomExist
            = link_to user_room_path(user.id, @roomId), data: {"turbolinks" => false} do
              .btn.btn-success
                | chatする
          - else
            = link_to user_rooms_path(user.id), method: :post, data: {"turbolinks" => false} do
              .btn.btn-success
                | chatする
.row
  = link_to '', edit_user_path(user), class:'btn btn-outline-secondary btn-block fas fa-user-cog'
h2.mt-3
  | New book
= form_with model: book, url: books_path, local: true do |f|
  .form-group
    label[for="book_title"]
      | Title
    input#book_title.form-control[type="text" name="book[title]"]
  .form-group
    label[for="book_opinion"]
      | Opinion
    textarea#book_opinion.form-control[name="book[body]"]
  button.btn.btn-success[type="submit"]
    | Create Book

app/views/layouts/_sidebar_follow.html.slim
- if not current_user.id == user.id
  - if current_user.following?(user)
    = link_to user_relationship_path(user.id, current_user.id), method: :delete do
      .btn.btn-secondary
        | フォロー外す
  - else
    = link_to user_relationships_path(user.id), method: :post do
      .btn.btn-success
        | フォローする

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Bookers2
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    header
      = render 'layouts/header'
    main
      p#notice
        = render 'layouts/notifications'
      = render 'searches/search', user: @user
      = yield
    footer
      = render 'layouts/footer'